version: '3'

volumes:
  esdata_local:

services:

  database:
    image: mysql:5.7
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: 'sheep'
    ports:
      - "3306:3306"
    volumes:
      - "/Users/xianghangxi/Docker/mysql/data:/var/lib/mysql"

  redis:
    image: redis
    container_name: blog_redis
    ports:
    - "6379:6379"

  web:
    build:
      context: .
      dockerfile: compose/local/Dockerfile
    volumes:
      - .:/blog_project
    ports:
      - "8000:8000"
    links:
      - database
      - redis
      - elasticsearch_local
    depends_on:
      - database
      - redis
      - elasticsearch_local
    command: /start.sh

  elasticsearch_local:
    build:
      context: .
      dockerfile: ./compose/production/elasticsearch/Dockerfile
    image: elasticsearch_local
    container_name: elasticsearch_local
    volumes:
      - esdata_local:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nproc: 65536
      nofile:
        soft: 65536
        hard: 65536
