version: '3'

volumes:
  database_local:

services:

  database_local:
    image: mysql:5.7
    container_name: blog-database-local
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci --init-connect='SET NAMES UTF8;' --innodb-flush-log-at-trx-commit=0

    environment:
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_USER: "${DB_USER}"
      MYSQL_PASSWORD: "${DB_PW}"
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PW}"

    ports:
      - "3306:3306"
    volumes:
      - database_local:/var/lib/mysql

#  redis_local:
#    build:
#    context: .
#    dockerfile: compose/production/Redis/Dockerfile
#    image: redis
#    container_name: blog-redis-local
#    ports:
#    - "6379:6379"

  web-local:
    build:
      context: .
      dockerfile: compose/local/Dockerfile
    image: blog_web_local
    container_name: blog-web-local
    volumes:
      - .:/blog_project
    ports:
      - "8000:8000"
    links:
      - database_local
#      - redis_local
    depends_on:
      - database_local
#      - redis_local
    command: /start.sh
