version: '3'

volumes:
  static_pdct:
  database_pdct:

services:
  web-pdct:
    build:
      context: .
      dockerfile: compose/production/Django/Dockerfile
    image: blog_web_pdct
    container_name: blog-web-pdct # 不能带下划线，不然Django 报错
    working_dir: /blog_project
    volumes:
      - static_pdct:/blog_project/static
    ports:
      - "8000:8000"
    links:
      - database-pdct
      - redis-pdct
    depends_on:
      - database-pdct
      - redis-pdct
    command: /start.sh

  ngnix-pdct:
    build:
      context: .
      dockerfile: compose/production/nginx/Dockerfile
    image: blog_ngnix_pdct
    container_name: blog-ngnix-pdct
    volumes:
    - static_pdct:/apps/blog_project/static
    ports:
    - "80:80"
    - "443:443"
    depends_on:
      - web-pdct

  redis-pdct:
    build:
      context: .
      dockerfile: compose/production/Redis/Dockerfile
    image: redis
    container_name: blog-redis-pdct
    ports:
      - "6379:6379"

  database-pdct:
    image: mysql:5.7
    container_name: blog-database-pdct
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci --init-connect='SET NAMES UTF8;' --innodb-flush-log-at-trx-commit=0

    environment:
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_USER: "${DB_USER}"
      MYSQL_PASSWORD: "${DB_PW}"
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PW}"

    ports:
      - "3306:3306"
    volumes:
      - database_pdct:/var/lib/mysql